// Samebase source build: v1997
/// <reference types="node" />
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

import { prerenderPages, type PrerenderPage } from "../prerender.config.ts";

export const generatedRedirectsStartTag = "# @samebase/base-prerender-redirects:start";
export const generatedRedirectsEndTag = "# @samebase/base-prerender-redirects:end";

const redirectsFilePath = path.resolve("public/_redirects");

function assertRedirectPath(label: string, value: string) {
  if (!value.startsWith("/")) {
    throw new Error(`${label} must be root-relative: ${value}`);
  }
}

function readHtmlOutputPath(page: PrerenderPage) {
  if (page.path === "/" && !page.prerender.outputPath) {
    throw new Error(
      "The root prerender page must set outputPath because Cloudflare SPA mode owns /index.html.",
    );
  }

  const outputPath = page.prerender.outputPath ?? `${page.path}/index.html`;
  const htmlOutputPath = outputPath.endsWith(".html") ? outputPath : `${outputPath}.html`;

  assertRedirectPath("Prerender output path", htmlOutputPath);
  if (htmlOutputPath === "/index.html") {
    throw new Error(
      "Prerender pages must not output /index.html because Cloudflare SPA mode serves that file for unknown app routes.",
    );
  }

  return htmlOutputPath;
}

function createRedirectAliases(routePath: string) {
  assertRedirectPath("Prerender route path", routePath);
  if (routePath === "/") {
    return ["/"];
  }

  return [routePath, `${routePath}/`];
}

export function buildGeneratedRedirects(pages: readonly PrerenderPage[]) {
  const redirectGroups = pages.map((page) => {
    const outputPath = readHtmlOutputPath(page);
    return [
      `${outputPath} ${page.path} 301`,
      ...createRedirectAliases(page.path).map((alias) => `${alias} ${outputPath} 200`),
    ].join("\n");
  });

  return [
    "# Generated by vp run generate:cloudflare-redirects.",
    "# Cloudflare SPA mode serves /index.html for unknown app routes, so",
    "# the SPA shell owns that file. Generated HTML file URLs redirect to",
    "# their canonical routes before exact aliases expose prerendered pages.",
    "",
    redirectGroups.join("\n\n"),
  ].join("\n");
}

function findMarkerLine(args: { lines: readonly string[]; marker: string }) {
  let markerLine: number | null = null;

  for (const [index, line] of args.lines.entries()) {
    if (line.trim() !== args.marker) {
      continue;
    }
    if (markerLine !== null) {
      throw new Error(`Expected exactly one ${args.marker} marker in public/_redirects.`);
    }

    markerLine = index;
  }

  if (markerLine === null) {
    throw new Error(`Missing ${args.marker} marker in public/_redirects.`);
  }

  return markerLine;
}

export function replaceGeneratedRedirectsBlock(contents: string, generatedRedirects: string) {
  const normalizedContents = contents.replace(/\r\n/g, "\n");
  const lines = normalizedContents.split("\n");
  const startLine = findMarkerLine({ lines, marker: generatedRedirectsStartTag });
  const endLine = findMarkerLine({ lines, marker: generatedRedirectsEndTag });

  if (startLine >= endLine) {
    throw new Error("The Cloudflare redirects start marker must come before the end marker.");
  }

  const nextContents = [
    ...lines.slice(0, startLine + 1),
    ...generatedRedirects.split("\n"),
    ...lines.slice(endLine),
  ].join("\n");

  return nextContents.endsWith("\n") ? nextContents : `${nextContents}\n`;
}

export function updateRedirectsFile(filePath = redirectsFilePath) {
  const contents = readFileSync(filePath, "utf8");
  const generatedRedirects = buildGeneratedRedirects(prerenderPages);
  const nextContents = replaceGeneratedRedirectsBlock(contents, generatedRedirects);

  if (nextContents === contents) {
    return;
  }

  writeFileSync(filePath, nextContents, "utf8");
}

const entrypoint = process.argv[1];
if (entrypoint && import.meta.url === pathToFileURL(entrypoint).href) {
  updateRedirectsFile();
}
