// Samebase source build: v1997
import { describe, expect, it } from "vite-plus/test";

import { prerenderPages } from "../prerender.config.ts";
import {
  buildGeneratedRedirects,
  generatedRedirectsEndTag,
  generatedRedirectsStartTag,
  replaceGeneratedRedirectsBlock,
} from "./generate-cloudflare-redirects.ts";

describe("generate-cloudflare-redirects", () => {
  it("creates exact aliases from public prerender pages", () => {
    expect(buildGeneratedRedirects(prerenderPages)).toBe(
      [
        "# Generated by vp run generate:cloudflare-redirects.",
        "# Cloudflare SPA mode serves /index.html for unknown app routes, so",
        "# the SPA shell owns that file. Generated HTML file URLs redirect to",
        "# their canonical routes before exact aliases expose prerendered pages.",
        "",
        "/_landing.html / 301",
        "/ /_landing.html 200",
        "",
        "/about/index.html /about 301",
        "/about /about/index.html 200",
        "/about/ /about/index.html 200",
      ].join("\n"),
    );
  });

  it("replaces only the tagged generated block", () => {
    const contents = [
      "/legacy /new 301",
      generatedRedirectsStartTag,
      "/old /old.html 200",
      generatedRedirectsEndTag,
      "/external https://example.com 302",
      "",
    ].join("\n");

    expect(replaceGeneratedRedirectsBlock(contents, buildGeneratedRedirects(prerenderPages))).toBe(
      [
        "/legacy /new 301",
        generatedRedirectsStartTag,
        "# Generated by vp run generate:cloudflare-redirects.",
        "# Cloudflare SPA mode serves /index.html for unknown app routes, so",
        "# the SPA shell owns that file. Generated HTML file URLs redirect to",
        "# their canonical routes before exact aliases expose prerendered pages.",
        "",
        "/_landing.html / 301",
        "/ /_landing.html 200",
        "",
        "/about/index.html /about 301",
        "/about /about/index.html 200",
        "/about/ /about/index.html 200",
        generatedRedirectsEndTag,
        "/external https://example.com 302",
        "",
      ].join("\n"),
    );
  });

  it("requires the generated block tags", () => {
    expect(() => replaceGeneratedRedirectsBlock("/ /_landing.html 200\n", "")).toThrow(
      "Missing # @samebase/base-prerender-redirects:start",
    );
  });

  it("keeps Cloudflare SPA shell ownership of /index.html", () => {
    expect(() =>
      buildGeneratedRedirects([
        {
          path: "/",
          prerender: {
            enabled: true,
            outputPath: "/index.html",
          },
        },
      ]),
    ).toThrow("Cloudflare SPA mode serves that file");
  });
});
